name: Build custom_jpegview VS2019

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Release x64
      shell: cmd
      run: |
        msbuild JPEGView.sln ^
          /m ^
          /p:Configuration=Release ^
          /p:Platform=x64

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: JPEGView-x64
        path: |
          JPEGView/bin/x64/Release/*.exe
          JPEGView/bin/x64/Release/*.dll
